### ISSUE TITLE
Import Error: undefined symbol: _Py_CheckRecursionLimit

### ISSUE THREAD

**Issue by DanXu-git** [bnr-cdx/prophet#1]
Hello, when I ran mrd_pyflow.py, I got the Python Import Error:
"
  File "mrd_pyflow.py", line 4, in <module>
    from umi_dedup_duplex import run_umi_extract_consensus
ImportError: /prophet/umi_dedup_duplex.so: undefined symbol: _Py_CheckRecursionLimit
"

Here's my environment information:
Python = 3.10.8
System = Ubuntu

What problem could this be?

**Comment by bnr-cdx** [comment]
Hi,  the core codes were compressed with python 3.6.4, maybe you could try running it with this version of python.

**Comment by DanXu-git** [comment]
> Hi, the core codes were compressed with python 3.6.4, maybe you could try running it with this version of python.

Thanks a lot, this solved my problem after I create a environment of Python 3.6.4.
